### PR TITLE
add ORGANIZATION.md

### PR DESCRIPTION
**Pull request by chrisplatorres**
continuation of #892 

This PR proposes adding a ORGANIZATION.md that outlines the directories in the Exokit repo.

--------------------------------------------

Inspired by A-Frame project's [ORGANIZATION.md](https://github.com/aframevr/aframe/blob/master/ORGANIZATION.md).

### CODE REVIEW

**Comment by chrisplatorres** [comment]
The concern for this PR is that it is susceptible to being broken by any given PR. The solution could be reviewing every PR through the frame of "will this PR break any current docs/ require new documentation?"

**Comment by chrisplatorres** [comment]
After looking at this doc again, I'm not sure it is useful, it is repeating `file name` + `redundant/obvious description`.

**Comment by shawwn** [comment]
I think it's useful. Most projects have an equivalent. There's also something to be said for seeing overall structure at a glance.
image

My nit is actually the name. I thought `ORGANIZATION.md` was referring to exokit the organization, not the organization of exokit.

**Comment by shawwn** [comment]
e.g. it's not obvious *at all* that `deps/exokit-bindings/browser` is related to CEF. The description makes it obvious.

**Comment by chrisplatorres** [comment]
Is there a better name for it? The `ORGANIZATION.md` name was inspired by the aframe repo: https://github.com/aframevr/aframe/blob/master/ORGANIZATION.md

**Comment by modulesio** [comment]
`DIRECTORIES` or `STRUCTURE`?

**Comment by shawwn** [comment]
Eh, ORGANIZATION.md is fine. I kinda regret mentioning it.

**Pull request closed without merging**
