### PR TITLE
Added initial dat support

### LINKED ISSUE #1213: Support for custom protocols in resource loader
This is to follow up from our discussions on Discord and to keep stuff in one place.

It'd be nice to be able to load resources in Exokit from different protocols, such as [dat://](https://dat.foundation/).

Currently there's no single place that resources are loaded that would handle this use case. With that in mind, here's what needs to be done:

- [ ] Rework [window-xhr](https://github.com/modulesio/window-xhr/issues/5) to use fetch to consolidate resource loading
- [ ] Add intercepts to [window-fetch](https://github.com/modulesio/window-fetch) for custom protocols
- [x] Implement [dat-fetch](https://github.com/RangerMauve/dat-fetch) which taks a DatArchive instance and exposes fetch. Based on [dat-fetch](https://github.com/RangerMauve/load-dat-page/blob/master/XHRPatcher.js#L69)
- [ ] Modify the `fetch` at the [top level of exokit frames](https://github.com/exokitxr/exokit/blob/master/src/WindowBase.js#L23), and the one used for [synchronous script loading](https://github.com/exokitxr/exokit/blob/master/src/request.js#L20)  to make use of the dat-enhanced fetch. Use [node-dat-archive](https://github.com/beakerbrowser/node-dat-archive) to start.
- [ ] Test loading content from `dat://` URLs

This might also be useful for the `exokit://` protocol handler stuff that's already in there.

### PR DESCRIPTION
**Pull request by RangerMauve**
Supports loading URLs from the `dat://` protocol. 

You can test it out with

```
exokit -x webvr dat://55861001e843ad2a0d0c1e1274c07cbc4fffa0a7cd83648741bc93c55c027acf/index.html
```

- Ensures that all protocols get a `://` after the protocol
- Adds dat-fetch to the protocols list
- Adds dat to the list f protocols to normalize

TODO:

- Figure out how to get the Dat libraries to work without process.nextTick
- Have the regex which detects protocols pull from the list of protocols in fetch.js?
- Configure persistent storage for Dat archives

Closes #1213

### CODE REVIEW

**Comment by shawwn** [comment]
I spent weeks arguing for decentralization in the context of webXR, and modulesio said it was dumb and highly unlikely. Yet here we are.

+1, hope this gets merged.

**Comment by modulesio** [comment]
Thanks for bootstrapping this experimentation @RangerMauve!

**Comment by modulesio** [comment]
@shawwn please review https://github.com/exokitxr/exokit/blob/master/CODE_OF_CONDUCT.md.

The Exokit Github repo is not the place for taking up personal issues with contributors.

**Comment by shawwn** [comment]
I have reviewed the code of conduct. Which area specifically do you feel my behavior violates?

I think I was kind and courteous in my "I told you so" comment.

**Comment by shawwn** [comment]
I also had no personal issue. Ideas are not personal; you seem to take them personally, however.

**Comment by shawwn** [comment]
That said, if you're looking for an excuse to ban me, I guess there's nothing to be done about that. It's your project.

**Comment by shawwn** [comment]
Excuse me, but please don't delete my comments. I asked a fair question.

Which part of the code of conduct does my behavior violate? You never answered.

I was kind and courteous in my reply.

**Comment by modulesio** [comment]
These comments are not related to Mauve’s pull request. Can we take this to another channel?

**Comment by modulesio** [comment]
Sorry @RangerMauve, this one got accidentally closed with a force-push. Did you want to re-open it? 🙏

**Comment by RangerMauve** [comment]
Yeah! Re-opening would be nice. I can't do it myself though. Otherwise I can open a new PR once I've made more progress. 😁

**Pull request closed without merging**
