### PR TITLE
Update node versions 11.6.0 -> 12.0.0

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR updates any docs and paths that are node version `11.6.0` to `12.0.0`. 

This is for the `user-parallel` #760 and #877 move to [Node 12](https://nodejs.org/ko/blog/release/v12.0.0/).

### CODE REVIEW

**Comment by modulesio** [comment]
This build is failing -- we should base it off of `here`: https://github.com/exokitxr/exokit/pull/1064

**Comment by modulesio** [comment]
Also, we are moving to `node` `12.2.0`, not strictly `12`.

**Comment by modulesio** [comment]
The way it shook out is the android/magic leap version will be `11.15.0` for now (required during build).

For desktop, however, it can be any version of `12`. Either way the `--experimental-worker` flag should no longer be required.

**Comment by chrisplatorres** [comment]
Ok I will update the android/magicleap cases.

**Comment by chrisplatorres** [comment]
Going to rebase this off `user-parallel`

**Pull request merged**
