### PR TITLE
add FakeVRDisplay's gamepads from globalGamepads

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR adds and assigns FakeVRDisplay's gamepads from globalGamepads.

### CODE REVIEW

**Comment by chrisplatorres** [comment]
This is missing the cases other than `main` gamepads.

**Comment by modulesio** [comment]
Should we be attaching these to the fake vr display going forward? This isn't a standard, so I think the more proper way would be to update the `realitytabs.html` example to use the proper APIs.

Also, I don't think we need to worry about non-main gamepads.

**Comment by chrisplatorres** [comment]
I don't understand, is this not the standard?
`navigator.getGamepads();`
https://github.com/exokitxr/exokit/blob/master/examples/realitytabs.html#L1873

**Comment by modulesio** [comment]
That part is fine; the part that's not is [decorating the display](https://github.com/exokitxr/exokit/pull/1098/files#diff-801f8b3e4342dd7a885d431f0dd9f72cR579).

Displays do not have gamepads, but you can query a matching gamepad with `navigator.getGamepads`.

**Comment by chrisplatorres** [comment]
> I think the more proper way would be to update the realitytabs.html example to use the proper APIs.

> Displays do not have gamepads, but you can query a matching gamepad with navigator.getGamepads.
  

You are meaning to decouple the gamepads from the FakeVRDisplay?

**Comment by modulesio** [comment]
> You are meaning to decouple the gamepads from the FakeVRDisplay?

Correct, that was never legal.

The `FakeVRDisplay` can and should still update the gamepads as required per emulation, but they should not be directly decorated on the display.

**Comment by chrisplatorres** [comment]
Makes sense, should we merge this fix for now and decouple it in a PR from master?

**Comment by modulesio** [comment]
No, I think that would be a regression. It seems the only reason for this code would be to fix `realitytabs.html`'s non-standard usage. That code is to be deleted with the studio anyway.

It's probably 20 lines in `realitytabs.html` that need to be changed to fix this usage.

**Comment by chrisplatorres** [comment]
Ok, I am going to revert the current changes in this branch and update the PR to fix `realitytabs.html` usage.

**Comment by modulesio** [comment]
Thanks, the fix would probably be basically the same thing, except in `realitytabs.html` instead of `VR.js`.

**Comment by chrisplatorres** [comment]
Now working, not sure if all the `var gamepads = navigator.getGamepads();`'s is redundant.

**Comment by modulesio** [comment]
Sweet! Should be ok, this code will be superceded by the studio.

**Pull request merged**
