### PR TITLE
Start xvfb for webgl testing on travis

### PR DESCRIPTION
**Pull request by shawwn**
I don't know whether this will work. This PR is to check whether Travis is happy or not.

### CODE REVIEW

**Comment by modulesio** [comment]
Nice, does this do gl calls now? Has that been checked?

**Comment by modulesio** [comment]
This seemed to be on the right track. For posterity is there a technical reason for closing it?

**Comment by chrisplatorres** [comment]
This might be useful to add a "supported XR sites" test in CI that helps maintain a list of sites that are confirmed to open in XR.

**Comment by modulesio** [comment]
Closing due to being outdated.

**Pull request closed without merging**
