### PR TITLE
Multithreading (reality layers)

### PR DESCRIPTION
**Pull request by modulesio**
Exokit's architecture has up until this point been mostly singlethreaded. This means that the render loop, and all user code animation frames ran in the same thread. This is mostly because that is how `node` (used to) work.

However, this is problematic for several reasons:
- Web APIs are architected around the idea that user code runs alone in its own thread -- for example, network requests, image decode, web workers, service workers, audio service threads all expect to be run in parallel to user code, not in the user thread 
- User threads can hold up the processing of network requests, resulting in needlessly reduced network throughput when doing heavy user work such as rendering
- User thread lockups can lock up Exokit engine entirely
- User contexts are very hard to track and destroy without encapsulating them inside of a true isolated V8 context environment
- Bugs from one context can leak to other contexts
- When Exokit loads and composes multiple WebXR iframes into a single world view ("reality tabs"), we need to make sure slow apps do not hold up fast apps -- this implies a desynchronized render loop with reprojection for apps that can't keep up, and that's only possible if we run each app in its own thread separate from the top level render loop

Node 11+12 have [full threading support](https://nodejs.org/api/worker_threads.html), which mostly follows the WebWorker API.

This PR leverages `worker_threads` to run all user window code in parallel, separate from the render loop. The architecture is as follows:

- These is still a top level render loop, which has a list of top-level `window`s, corresponding to web `window` contexts
- The render loop asynchronously dispatches the XR three-phase events to the `window` contexts: `waitPose`, `tickAnimationFrame`, `submitFrame`. This is effected by posting messages down child `window`s, and capturing the response in a `Promise` which we can `.then` on
- Since each window can have child 3D `<iframe>`s which it is composing into its scene, each window is also its own render loop, and proxies the three-phase XR to its child windows. This forms a virtual render tree structure made of `window` contexts
- Use GLSync objects from the child `window` renders, waited on by its owning `window`, in order to effect perfect frame synchronization for apps in the ideal case
- If an app does not meet the frame deadline, we `setTimeout` and continue rendering without it, and do not dispatch any more `requestAnimationFrame` to it -- whenever the app finishes the render and resolves the corresponding `Promise`, we will pick up the frame on the next available render loop tick and resume further `requestAnimationFrame` to it
- Everything else works normally as if we had multiple V8/GC contexts, which is friendly to OS threading, scheduling and allocation

Though this PR does not do it yet, this opens up the path to full Service Worker and audio thread support, as well as 3D framebuffer reprojection support for applications so that we maintain frame rate even in cases where the user code cannot keep up (due to loading, being badly written, etc).

Most of the changes here are instituting the new render loop request/response, and fixing the places in the code that assumed everything was running synchronously in one thread.

Overall user code should see no change here, other than that everything becomes faster for free, especially -- but not only -- when using reality tabs in XR. 🦄 🌈

### CODE REVIEW

**Comment by modulesio** [comment]
Note this is currently based on `window-renderloop`, not `master`.

**Comment by modulesio** [comment]
This should be building now.

**Comment by chrislatorres** [comment]
Tested each example as reality tab on new `user-parallel` mpk:

------------------------------------------

Works as a reality tab:
```
paint_ml
tutorial
exobot
minimap "works", but don't see anything?
radar
microphone 
```
------------------------------------------

Blank as a reality tab, no errors or hard crash:
```
hello_ml
meshing_ml
planes_ml
graffiti_ml
hands_ml
bow_ml
pathfinding_ml
imagetracking_ml
```
------------------------------------------

Crashes with the following error:

`FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope`
```
avatar_ml
shooter_ml , when pull trigger
```

**Comment by modulesio** [comment]
The above errors are due to the new threading model requiring the magic leap bindings to dispatch events to the correct thread, which was not a concern before.

**Comment by modulesio** [comment]
The magic leap threading errors should be fixed; needs a re-test.

**Comment by modulesio** [comment]
For macOS, we need to make sure we are creating reality tabs GLFW contexts on the main thread. This looks like a Cocoa restriction:

```
node --experimental-worker .
2019-03-26 17:09:07.652 node[27682:2326667] WARNING: nextEventMatchingMask should only be called from the Main Thread! This will throw an exception in the future.
2019-03-26 17:09:07.652 node[27682:2326667] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1561/Foundation/Misc.subproj/NSUndoManager.m:361
2019-03-26 17:09:07.653 node[27682:2326667] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1561/Foundation/Misc.subproj/NSUndoManager.m:361
2019-03-26 17:09:07.683 node[27682:2326667] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3b6c3ecd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6777b720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3b6deb2a +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff3da82e0d -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff3d9b3249 +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 469
	5   AppKit                              0x00007fff38b5624e -[NSApplication run] + 932
	6   exokit.node                         0x00000001062c43e4 initializeAppKit + 436
	7   exokit.node                         0x00000001062c409d _glfwPlatformCreateWindow + 29
	8   exokit.node                         0x00000001062bb073 glfwCreateWindow + 1059
	9   exokit.node                         0x0000000106278a4c _ZN4glfw18CreateNativeWindowEjjbP10GLFWwindow + 327
	10  exokit.node                         0x000000010627fc79 _ZNSt3__114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEZN4glfw18CreateWindowHandleERKN3Nan20FunctionCallbackInfoIN2v85ValueEEEE4$_19EEEEEPvSH_ + 74
	11  libsystem_pthread.dylib             0x00007fff68a3d305 _pthread_body + 126
	12  libsystem_pthread.dylib             0x00007fff68a4026f _pthread_start + 70
	13  libsystem_pthread.dylib             0x00007fff68a3c415 thread_start + 13
```

**Comment by modulesio** [comment]
For CI, we'll need to update the tests to make `window` threads instead of decorating a local object:

```
TypeError: GlobalContext._makeWindow is not a function
      at Context.it (/app/tests/unit/Document.test.js:12:34)
      at callFn (/app/node_modules/mocha/lib/runnable.js:387:21)
      at Test.Runnable.run (/app/node_modules/mocha/lib/runnable.js:379:7)
      at Runner.runTest (/app/node_modules/mocha/lib/runner.js:525:10)
      at /app/node_modules/mocha/lib/runner.js:643:12
      at next (/app/node_modules/mocha/lib/runner.js:437:14)
      at /app/node_modules/mocha/lib/runner.js:447:7
      at next (/app/node_modules/mocha/lib/runner.js:362:14)
      at Immediate._onImmediate (/app/node_modules/mocha/lib/runner.js:415:5)
      at processImmediate (timers.js:632:19)
      at process.topLevelDomainCallback (domain.js:120:23)
```

**Comment by modulesio** [comment]
We'll need to update the tests to not use old internal functions that don't exist in the isolated parallel `window` contexts:

```
GlobalContext._makeWindow is not a function
```

**Comment by modulesio** [comment]
The multi-`window` worker thread tests are failing for two reasons:
- They need to be refactored to isolated parallel `window`-style
- The main exokit native binding throws when loading

Luckily there is only a few files for each so it should be easy to bisect to the right line.

**Comment by chrisplatorres** [comment]
Testing displaced reality tabs, a-painter, and specifically for magic leap; the magic leap api examples.
- [ ] android
- [ ] magic leap + API examples
- [ ] windows
- [ ] macos
- [ ] linux

**Comment by chrisplatorres** [comment]
**note: each platform requires [a trailing slash for a-painter](https://github.com/exokitxr/exokit/issues/1025)**.
**note: running a-frame as a reality tab `-t` required running multiple times before the race condition error did not occur.**

  
------------------------------------
# ✅ Linux/ubuntu testing  
✅ opened multiple exobot tabs and tested displacement successfully
✅ opened a-painter `node --experimental-worker . -x webvr https://aframe.io/a-painter/` succesfully
✅ opening a-painter as a tab was successful `node --experimental-worker . -x webvr -h -t https://aframe.io/a-painter/`

# ✅ macOS testing
✅ opened multiple exobot tabs and tested displacement successfully
✅ opened a-painter `node --experimental-worker . -x webvr https://aframe.io/a-painter/` succesfully
✅ opening a-painter as a tab was successful `node --experimental-worker . -x webvr -h -t https://aframe.io/a-painter/`

# ✅ Windows testing
✅ opened multiple exobot tabs and tested displacement successfully
✅ opened a-painter `node --experimental-worker . -x webvr https://aframe.io/a-painter/` succesfully
✅ opening a-painter as a tab was successful `node --experimental-worker . -x webvr -h -t https://aframe.io/a-painter/`



# Magic Leap testing 

When testing hello_ml / meshing example on Exokit MPK
```
05-07 00:02:59.458  1585     3 E exokit  : Error: MLContext::RequestMeshing: invalid arguments
05-07 00:02:59.458  1585     3 E exokit  :     at Object.RequestMeshing (/package/src/Window.js:959:38)
05-07 00:02:59.458  1585     3 E exokit  :     at _enable (file:///package/examples/hello_ml.html:358:43)
05-07 00:02:59.458  1585     3 E exokit  :     at init (file:///package/examples/hello_ml.html:385:9)
05-07 00:02:59.458  1585     3 E exokit  :     at file:///package/examples/hello_ml.html:459:5
05-07 00:02:59.458  1585     3 E exokit  :     at Script.runInThisContext (vm.js:123:20)
05-07 00:02:59.458  1585     3 E exokit  :     at Object.runInThisContext (vm.js:312:38)
05-07 00:02:59.458  1585     3 E exokit  :     at /package/src/DOM.js:1740:12
05-07 00:02:59.458  1585     3 E exokit  :     at Resource.ownerDocument.resources.addResource [as getCb] (/package/src/DOM.js:1745:9)
05-07 00:02:59.458  1585     3 E exokit  :     at Promise (/package/src/Document.js:272:12)
05-07 00:02:59.458  1585     3 E exokit  :     at new Promise (<anonymous>)
```

When testing a-painter on Exokit MPK ( `./scripts/run-ml.sh "-x webvr https://aframe.io/a-painter/"` ):

```
05-07 00:12:06.336  2171     3 E exokit  : TypeError: Cannot read property 'el' of undefined
05-07 00:12:06.336  2171     3 E exokit  :     at HTMLElement.value (vendor/aframe-master.min.js:482:5626)
05-07 00:12:06.336  2171     3 E exokit  :     at enterVRBound (vendor/aframe-master.min.js:482:3198)
05-07 00:12:06.336  2171     3 E exokit  :     at emit (events.js:188:13)
05-07 00:12:06.336  2171     3 E exokit  :     at EventEmitter.emit (domain.js:441:20)
05-07 00:12:06.336  2171     3 E exokit  :     at _emit (/package/src/Event.js:60:40)
05-07 00:12:06.336  2171     3 E exokit  :     at window._emit (/package/src/Window.js:1125:28)
05-07 00:12:06.336  2171     3 E exokit  :     at _emit (/package/src/Event.js:38:14)
05-07 00:12:06.336  2171     3 E exokit  :     at _recurse (/package/src/Event.js:46:7)
05-07 00:12:06.336  2171     3 E exokit  :     at dispatchEvent (/package/src/Event.js:56:5)
05-07 00:12:06.336  2171     3 E exokit  :     at _emitOneDisplay (/package/src/Document.js:223:16)
```

When running a-painter as a tab: `./scripts/run-ml.sh "-x webvr -h -t https://aframe.io/a-painter/"`
```
05-07 00:13:12.005  2344     2 I exokit  : frameworks/libs/llcommcpp/llcomm_helpers/impl/llcomm_helpers.cpp(256) SafeQueryByTime():
05-07 00:13:12.005  2344     2 I exokit  : ERR: reason=llcomQueryError,handle_name=XVUjdJR_dYKV75,time_us=18446744073709551615,status=23=LLCOMM_PERMISSION_DENIED
05-07 00:13:12.005  2344     2 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(288) Update():
05-07 00:13:12.005  2344     2 I exokit  : ERR: [ LLComm ] Failed to complete query for [ gesture_llcomm ].
05-07 00:13:12.007  2344     2 I exokit  : request present
05-07 00:13:12.007  2344     3 E exokit  : TypeError: Cannot read property 'device' of undefined
05-07 00:13:12.007  2344     3 E exokit  :     at VRDisplay.requestPresent (/package/src/VR.js:277:18)
05-07 00:13:12.405  2344     1 E NoTag   : MLGraphicsBeginFrame complained: 2
05-07 00:13:12.656  2344     1 E NoTag   : MLGraphicsBeginFrame complained: 2
05-07 00:13:12.908  2344     1 E NoTag   : MLGraphicsBeginFrame complained: 2
05-07 00:13:13.159  2344     1 E NoTag   : MLGraphicsBeginFrame complained: 2
05-07 00:13:13.411  2344     1 E NoTag   : MLGraphicsBeginFrame complained: 2
05-07 00:13:13.473  2344     2 I exokit  : frameworks/perception/src/trackers/hand_tracker_llcomm.cpp(291) Update():
05-07 00:13:13.473  2344     2 I exokit  : ALW: [ LLComm ] Successfully queried for [ gesture_llcomm ].
```

**Comment by modulesio** [comment]
Thanks! 👏

```
05-07 00:12:06.336  2171     3 E exokit  : TypeError: Cannot read property 'el' of undefined
05-07 00:12:06.336  2171     3 E exokit  :     at HTMLElement.value (vendor/aframe-master.min.js:482:5626)
05-07 00:12:06.336  2171     3 E exokit  :     at enterVRBound (vendor/aframe-master.min.js:482:3198)
```

This one was a manifestation of the race condition, no?

**Comment by chrisplatorres** [comment]
Yes, I am going to try again on MLO to get past that error.

**Comment by chrisplatorres** [comment]
# ❌ Oculus Mobile:

- tried running `./scripts/run-android.sh`  
- tried running a-painter ` adb shell am start -n com.webmr.exokit/android.app.NativeActivity -e ARGS "'node --experimental-worker /package -x webvr https://aframe.io/a-painter/'"`  
- tried running Exokit app from Oculus library  

❌ No success for any, going to pinpoint where it is failing. (the oculus mobile adb logcat is very verbose relative to the MPK mldb log)

**Comment by modulesio** [comment]
Re: oculus, remember that the OS will not often not relaunch apps that are launched, so the app must be [force-terminated every time](https://github.com/exokitxr/exokit/blob/51a1534c4dab36be9bd0a25fe60e400df010637d/scripts/run-android.sh#L12).

Running the start command alone does not work when debugging -- that is not how Android Activities work.

For the logging, be on the lookout for `exokit` in the `grep`. We try to be pretty verbose about the startup phase at lease.

**Comment by chrisplatorres** [comment]
> Running the start command alone does not work when debugging -- that is not how Android Activities work.

I should clarify that the 
` adb shell am start -n com.webmr.exokit/android.app.NativeActivity -e ARGS "'node --experimental-worker /package -x webvr https://aframe.io/a-painter/'" `

was a line replacement in https://github.com/exokitxr/exokit/blob/master/scripts/run-android.sh#L14 for:
`adb shell am start -n com.webmr.exokit/android.app.NativeActivity`

**Comment by modulesio** [comment]
The race condition to enter A-Painter might have been fixed with https://github.com/exokitxr/exokit/commit/40f3531468107f4a16c82d844ba57635e22d882e

**Comment by chrisplatorres** [comment]
# Notes
- ✅ every OS runs `node --experimental-worker . -x webvr https://aframe.io/a-painter` fine now (no race condition error)
- ❌ every OS runs `node --experimental-worker . -x webvr -h -t https://aframe.io/a-painter` and gets 404 errors from missing the trailing slash (this only happens when opening as a tab though)

# Running a-painter as a tab
❌ Running `node --experimental-worker . -x webvr -h -t https://aframe.io/a-painter/` has incorrect sizing for a-painter on **macOS** and **linux**.

## ❌ macOS 
apainterCapture
## ❌ Linux 
apaintScreenshot_from_2019-05-08_00-02-33
2Screenshot_from_2019-05-08_00-07-42

## ✅ Windows
windCapture

**Comment by chrisplatorres** [comment]
Tracking:


- [ ] Magic Leap RequestMeshing invalid argument
    - https://github.com/exokitxr/exokit/blob/99a345e8ae266a70d54e99de850e6ef95cb141d0/deps/exokit-bindings/magicleap/src/magicleap.cc#L3676
- [ ] A-Frame missing trailing slash 404s when ran as a tab
    - https://github.com/exokitxr/exokit/blob/b4631536cbe1b8c29cf51cfc4e7bdf58970d8d8e/src/index.js#L2320

- [ ] magic leap
    - [x] displaced reality layers
    - [ ] a-painter
    - [ ] a-painter as a reality layer
    - [ ] magic leap API examples
- [ ] oculus mobile 
    - [ ] displaced reality layers
    - [ ] a-painter
    - [ ] a-painter as a reality layer

**Comment by modulesio** [comment]
Based on the above blits, I wonder if this has to do with `devicePixelRatio`. Would be good to know the setting for the above OSes:

```
window.devicePixelRatio
```

**Comment by modulesio** [comment]
@chrisplatorres Are you able to check whether [this PR](https://github.com/exokitxr/exokit/pull/1033) fixes the eye metrics issue on the systems you were testing on?

**Comment by chrisplatorres** [comment]
` user-parallel-blit` did not fix the issue, it is still occurring on macOS and linux.

**Comment by modulesio** [comment]
Was that on headset, or just desktop?

**Comment by chrisplatorres** [comment]
Desktop, running fakedisplay:

`node --experimental-worker . -x webvr -h -t https;//aframe.io/a-painter/`

**Comment by modulesio** [comment]
Does it look any different (are the eyes in full view?) Or is it exactly the same cut-off as in the above screenshots?

**Comment by chrisplatorres** [comment]
Same cut-off, new screenshots:

Screenshot_from_2019-05-08_17-55-51
nodifCapture

**Comment by chrisplatorres** [comment]
No longer tracking the meshing issue in this branch, but commenting here for future context:

> meshing probably doesn't need to be fixed in user-parallel, there is a total refactor of it in studio

- Magic Leap RequestMeshing invalid argument
    - https://github.com/exokitxr/exokit/blob/99a345e8ae266a70d54e99de850e6ef95cb141d0/deps/exokit-bindings/magicleap/src/magicleap.cc#L3676

```sh
05-07 00:02:59.458  1585     3 E exokit  : Error: MLContext::RequestMeshing: invalid arguments
05-07 00:02:59.458  1585     3 E exokit  :     at Object.RequestMeshing (/package/src/Window.js:959:38)
05-07 00:02:59.458  1585     3 E exokit  :     at _enable (file:///package/examples/hello_ml.html:358:43)
05-07 00:02:59.458  1585     3 E exokit  :     at init (file:///package/examples/hello_ml.html:385:9)
05-07 00:02:59.458  1585     3 E exokit  :     at file:///package/examples/hello_ml.html:459:5
05-07 00:02:59.458  1585     3 E exokit  :     at Script.runInThisContext (vm.js:123:20)
05-07 00:02:59.458  1585     3 E exokit  :     at Object.runInThisContext (vm.js:312:38)
05-07 00:02:59.458  1585     3 E exokit  :     at /package/src/DOM.js:1740:12
05-07 00:02:59.458  1585     3 E exokit  :     at Resource.ownerDocument.resources.addResource [as getCb] (/package/src/DOM.js:1745:9)
05-07 00:02:59.458  1585     3 E exokit  :     at Promise (/package/src/Document.js:272:12)
05-07 00:02:59.458  1585     3 E exokit  :     at new Promise (<anonymous>)
```

**Comment by RangerMauve** [comment]
Oh snap! Congrats! :D

**Pull request merged**
