### PR TITLE
Add --help

### PR DESCRIPTION
**Pull request by shawwn**

### CODE REVIEW

**Comment by modulesio** [comment]
This is a good idea, but is there some way to autogenerate this so it doesn't get out of sync with the actual arguments parsing?

**Comment by shawwn** [comment]
Not without reworking how the argument system works.

**Comment by modulesio** [comment]
Yes, I am recommending a slight refactor of that code for the sake of maintainability.

**Comment by modulesio** [comment]
This is not the right strategy for a `--help` documentation.

We might derive one from the docs at some point.

**Pull request closed without merging**
