### PR TITLE
Specify Lumin SDK v0.19 in Magic Leap One build instructions

### PR DESCRIPTION
**Pull request by chrisplatorres**

### CODE REVIEW

**Comment by modulesio** [comment]
What's needed to bump the SDK version?

**Comment by chrisplatorres** [comment]
For the latest Lumin SDK version (v0.22.0), this error happens due to

```
In file included from ../exokit.cpp:10:
In file included from c:\Users\chris\github\exo2\exokit\deps\exokit-bindings\bindings\inc
lude\bindings.h:26:
c:\Users\chris\github\exo2\exokit\deps\exokit-bindings\magicleap\include\magicleap.h:40:1
0: fatal error:
      'ml_gesture.h' file not found
#include <ml_gesture.h>
```

That header file does not exist in v0.22, below is looking for the file in the sdk directory, it is only found up to version 0.20.
```
MagicLeap$ find . -name "ml_gesture.h"
./mlsdk/v0.19.0/include/ml_gesture.h
./mlsdk/v0.20.0/include/ml_gesture.h
```

From the release notes below:
> ml_gestures.h is removed from the SDK, use ml_hand_tracking.h


---------------------------------------

### Lumin SDK Deprecation Notices

from v0.20 release notes:
```
Deprecation Notice
MLControllerCreate API was deprecated, use MLControllerCreateEx instead.
MLPersistentCoordinateFrameGetAll API was deprecated, use MLPersistentCoordinateFrameGetAllEx instead.
MLMusicServiceGetMetadata API was deprecated, use MLMusicServiceGetMetadataEx instead.
MLGraphicsClipExtentsInfoArray struct was deprecated, use MLGraphicsClipExtentsInfoArrayEx instead.
MLGraphicsGetClipExtents API was deprecated, use MLGraphicsGetClipExtentsEx instead.
MLMediaPlayerSubtitleFormat enum was deprecated, use ml_media_fromat.h to get the subtitle mime type.
MLMediaPlayerSubtitleData.format field was deprecated, use ml_media_fromat.h to get the subtitle mime type.
Although not indicated clearly, the MLDataArray interface should be considered deprecated, as the only users of this API (Gestures and Legacy Meshing) are both deprecated. We will be removing this interface along with gestures & legacy meshing next release (LuminSDK 0.21.0).
```

from v0.21 release notes:
```
Deprecation Notice
ml_meshing.h is removed from the SDK, use ml_meshng2.h
ml_gestures.h is removed from the SDK, use ml_hand_tracking.h
MLMusicServiceGetMetadataEx API was deprecated, use MLMusicServiceGetMetadataForIndex instead.
```

from v0.22 release notes:
```
Deprecation Notice
MLPlanesQueryGetResults API is removed from the SDK, use MLPlanesQueryGetResultsWithBoundaries instead.
PwFoundObjRead is deprecated, please use PcfRead privilege instead.
MLHandTrackingKeyPose_OpenHandBack enum is deprecated, please use MLHandTrackingKeyPose_OpenHand instead.
```

**Comment by modulesio** [comment]
Will need to update the usage in that case.

**Comment by chrisplatorres** [comment]
Closing in favor of #1400.

**Pull request closed without merging**
