### PR TITLE
add CHANGELOG.md

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR proposes adding a CHANGELOG.md to keep track of important commits.

> For release: go through each commit in the Git log since the last release and include every notable patch. The categories should be Major Changes, Deprecations, Enhancements, Performance, Bug Fixes. In each category, loosely sort the more impacting changes at the top.

Inspired by [A-Frame's release wiki](https://github.com/aframevr/aframe/wiki/Release-Process#a-frame).

### CODE REVIEW

**Comment by modulesio** [comment]
Might want to hold off merging until there is content here.

**Comment by modulesio** [comment]
I think the MacOS certificate needs to be updated for the CI to pass.

**Comment by chrisplatorres** [comment]
We can track the changelog using GitHub's milestones https://github.com/exokitxr/exokit/milestones

**Comment by chrisplatorres** [comment]
Closing in favor of #977

**Pull request closed without merging**
