### PR TITLE
Clean up docs content

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR proposes updates to the docs content which has many outdated relics of past Exokit versions.

### CODE REVIEW

**Comment by chrisplatorres** [comment]
need to wipe these dead pages (.md docs deleted, but static pages still are up) in exokit-site

https://exokit.org/docs/apis/experimentalWebAPIs.html
https://exokit.org/docs/guides/my-first-exokit-app.html ............. [static here](https://github.com/exokitxr/exokitxr.github.io/blob/master/docs/guides/my-first-exokit-app.html)

**Comment by chrisplatorres** [comment]
the privacy policy sounds very out of tone for what Exokit does https://exokit.org/docs/legal/privacy.html

**Comment by modulesio** [comment]
Yeah, that was to cover things beyond Exokit engine, which we're not doing. We should probably throw the whole thing out.

**Comment by chrisplatorres** [comment]
new doc pages needed:
- how to package an XR site and build an APK for oculus mobile
- how to package an XR site and build an MPK for magic leap one
- iframe API for reality tabs
- how to add a new native binding to exokit 
- add more to debugging doc (include gdb, winbgd)

------------------------------------------------
 
other notes
- update infographics
- add more gifs / images

**Comment by chrisplatorres** [comment]
Merging and start a new PR for adding new docs content.

**Pull request merged**
