### PR TITLE
Tutorial texture mipmapping

### PR DESCRIPTION
**Pull request by modulesio**
This increases the mipmap+filter quality for the `tutorial.html` instructions texture.

### CODE REVIEW

**Comment by chrisplatorres** [comment]
Improvement from #1101?

**Comment by chrisplatorres** [comment]
For comparison:

This PR:
tut1Capture

Master:
tut2Capture

**Comment by chrisplatorres** [comment]
This PR:
tut4Capture

Master:
tut3Capture

**Comment by modulesio** [comment]
Thanks for the shots, I think the improvements are clear in the second one. 👏 

It should be even more prominent in the headset.

**Comment by modulesio** [comment]
We can apply this same technique to the `realitytabs.html` UI now, as well as the studio UI texture in future.

**Pull request merged**
